# Generated by Django 4.1 on 2025-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("outpatient", "Bệnh nhân ngoại trú"),
                            ("inpatient", "Bệnh nhân nội trú"),
                            ("emergency", "Bệnh nhân cấp cứu"),
                            ("follow_up", "Bệnh nhân tái khám"),
                        ],
                        default="outpatient",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("prediction_history", models.TextField(blank=True)),
            ],
        ),
    ]
