# Generated by Django 4.1 on 2025-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("specialty", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("medical_doctor", "Bác sĩ thường"),
                            ("attending_physician", "Bác sĩ điều trị chính"),
                            ("department_head", "Trưởng khoa"),
                            ("resident", "Bác sĩ nội trú"),
                            ("intern", "Bác sĩ thực tập"),
                        ],
                        default="medical_doctor",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
